application: foosalizer
version: 1
runtime: python
api_version: 1

handlers:

- url: /static
  static_dir: static

- url: /admin/*.*
  script: admin.py
  login: admin

- url: /.*
  script: foosalizer.py
  login: required
